apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-extender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-extender
  template:
    metadata:
      labels:
        app: scheduler-extender
    spec:
      containers:
      - name: scheduler-extender
        image: {{ .Values.schedulerExtender.image }}
        ports:
        - containerPort: 9001
