// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: slo_service.proto

package slosv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TenantCreditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantCreditRequest) Reset() {
	*x = TenantCreditRequest{}
	mi := &file_slo_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantCreditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantCreditRequest) ProtoMessage() {}

func (x *TenantCreditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slo_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantCreditRequest.ProtoReflect.Descriptor instead.
func (*TenantCreditRequest) Descriptor() ([]byte, []int) {
	return file_slo_service_proto_rawDescGZIP(), []int{0}
}

func (x *TenantCreditRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

var File_slo_service_proto protoreflect.FileDescriptor

const file_slo_service_proto_rawDesc = "" +
	"\n" +
	"\x11slo_service.proto\x12\aapi.slo\x1a\tslo.proto\x1a\x1bgoogle/protobuf/empty.proto\"2\n" +
	"\x13TenantCreditRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId2\xe7\x01\n" +
	"\x13TenantCreditService\x12H\n" +
	"\x0fGetTenantCredit\x12\x1c.api.slo.TenantCreditRequest\x1a\x15.api.slo.TenantCredit\"\x00\x12E\n" +
	"\x0fRecordViolation\x12\x18.api.slo.ViolationRecord\x1a\x16.google.protobuf.Empty\"\x00\x12?\n" +
	"\x0fUpdateTenantSLO\x12\x12.api.slo.TenantSLO\x1a\x16.google.protobuf.Empty\"\x00B7Z5github.com/example/slo-scheduler/proto/api/slo;slosv1b\x06proto3"

var (
	file_slo_service_proto_rawDescOnce sync.Once
	file_slo_service_proto_rawDescData []byte
)

func file_slo_service_proto_rawDescGZIP() []byte {
	file_slo_service_proto_rawDescOnce.Do(func() {
		file_slo_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_slo_service_proto_rawDesc), len(file_slo_service_proto_rawDesc)))
	})
	return file_slo_service_proto_rawDescData
}

var file_slo_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_slo_service_proto_goTypes = []any{
	(*TenantCreditRequest)(nil), // 0: api.slo.TenantCreditRequest
	(*ViolationRecord)(nil),     // 1: api.slo.ViolationRecord
	(*TenantSLO)(nil),           // 2: api.slo.TenantSLO
	(*TenantCredit)(nil),        // 3: api.slo.TenantCredit
	(*emptypb.Empty)(nil),       // 4: google.protobuf.Empty
}
var file_slo_service_proto_depIdxs = []int32{
	0, // 0: api.slo.TenantCreditService.GetTenantCredit:input_type -> api.slo.TenantCreditRequest
	1, // 1: api.slo.TenantCreditService.RecordViolation:input_type -> api.slo.ViolationRecord
	2, // 2: api.slo.TenantCreditService.UpdateTenantSLO:input_type -> api.slo.TenantSLO
	3, // 3: api.slo.TenantCreditService.GetTenantCredit:output_type -> api.slo.TenantCredit
	4, // 4: api.slo.TenantCreditService.RecordViolation:output_type -> google.protobuf.Empty
	4, // 5: api.slo.TenantCreditService.UpdateTenantSLO:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_slo_service_proto_init() }
func file_slo_service_proto_init() {
	if File_slo_service_proto != nil {
		return
	}
	file_slo_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_slo_service_proto_rawDesc), len(file_slo_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_slo_service_proto_goTypes,
		DependencyIndexes: file_slo_service_proto_depIdxs,
		MessageInfos:      file_slo_service_proto_msgTypes,
	}.Build()
	File_slo_service_proto = out.File
	file_slo_service_proto_goTypes = nil
	file_slo_service_proto_depIdxs = nil
}
