name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build Go components
        run: |
          go build ./credit-service
          go build ./admission-controller
          go build ./scheduler-extender
          go build ./cgroup-adjuster
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build sidecar-agent
        run: cargo build --manifest-path sidecar-agent/Cargo.toml --release
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
      - name: Run lint
        run: golangci-lint run ./...
      - name: Run unit tests
        run: go test ./...
